EnvPrefix: dev
log:
  level: debug
server:
  basePath: /api
  address: 0.0.0.0:8081
  readtimeout: 30s
  writetimeout: 30s
  middlewares:
    enable:
      - auth
      - logger
      - requestid
      - limit
      - log
    auth:
      username: d1r1
      password: testpassword123
    limit:
      body: 100MB
    log: {}
    logger: {}
    requestid: {}
api: {}
services:
  ipfs:
    bootstrapList: [""]
    repo: "./data"
  orbitdb:
    privateKey: "d23f9e4b12bfda2f64fd8a3141db466a5856787d6cde70b9caafdc9af6bd5770"
    repo: "./data"
  eventlog:
    loadLimit: 100
