version: "3.6"
services:
  postgres:
    image: postgres
    container_name: postgres${DOCKER_ID}
    restart: on-failure
    ports: 
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./pg-init-scripts:/docker-entrypoint-initdb.d
    networks:
      - debridge-node-network
networks:
  debridge-node-network:
    name: debridge-node-network